var annotated_dup =
[
    [ "Nth", "namespace_nth.html", [
      [ "AudioEngine", "class_nth_1_1_audio_engine.html", "class_nth_1_1_audio_engine" ],
      [ "Behavior", "struct_nth_1_1_behavior.html", "struct_nth_1_1_behavior" ],
      [ "BehaviorDescriptor", "struct_nth_1_1_behavior_descriptor.html", "struct_nth_1_1_behavior_descriptor" ],
      [ "BehaviorEntity", "struct_nth_1_1_behavior_entity.html", "struct_nth_1_1_behavior_entity" ],
      [ "BehaviorScriptContext", "struct_nth_1_1_behavior_script_context.html", "struct_nth_1_1_behavior_script_context" ],
      [ "BindShaderCommand", "struct_nth_1_1_bind_shader_command.html", "struct_nth_1_1_bind_shader_command" ],
      [ "Camera", "struct_nth_1_1_camera.html", null ],
      [ "ClearCommand", "struct_nth_1_1_clear_command.html", "struct_nth_1_1_clear_command" ],
      [ "Clock", "class_nth_1_1_clock.html", "class_nth_1_1_clock" ],
      [ "Collider2D", "struct_nth_1_1_collider2_d.html", null ],
      [ "CollisionDetection", "class_nth_1_1_collision_detection.html", null ],
      [ "Color", "class_nth_1_1_color.html", "class_nth_1_1_color" ],
      [ "CommandExecutor", "class_nth_1_1_command_executor.html", "class_nth_1_1_command_executor" ],
      [ "CommandQueue", "class_nth_1_1_command_queue.html", "class_nth_1_1_command_queue" ],
      [ "Content", "class_nth_1_1_content.html", null ],
      [ "DebugManager", "class_nth_1_1_debug_manager.html", "class_nth_1_1_debug_manager" ],
      [ "DrawSpriteCommand", "struct_nth_1_1_draw_sprite_command.html", "struct_nth_1_1_draw_sprite_command" ],
      [ "EntityDescriptor", "struct_nth_1_1_entity_descriptor.html", "struct_nth_1_1_entity_descriptor" ],
      [ "Game", "class_nth_1_1_game.html", "class_nth_1_1_game" ],
      [ "Geometry", "class_nth_1_1_geometry.html", "class_nth_1_1_geometry" ],
      [ "IBuffer", "class_nth_1_1_i_buffer.html", "class_nth_1_1_i_buffer" ],
      [ "IDebugOverlay", "class_nth_1_1_i_debug_overlay.html", "class_nth_1_1_i_debug_overlay" ],
      [ "ImGuiDebugLayer", "class_nth_1_1_im_gui_debug_layer.html", "class_nth_1_1_im_gui_debug_layer" ],
      [ "IndexBuffer", "class_nth_1_1_index_buffer.html", "class_nth_1_1_index_buffer" ],
      [ "InputManager", "class_nth_1_1_input_manager.html", "class_nth_1_1_input_manager" ],
      [ "Log", "class_nth_1_1_log.html", "class_nth_1_1_log" ],
      [ "LuaRegisterable", "struct_nth_1_1_lua_registerable.html", "struct_nth_1_1_lua_registerable" ],
      [ "LuaRegistry", "struct_nth_1_1_lua_registry.html", "struct_nth_1_1_lua_registry" ],
      [ "LuaTypeRegistration", "struct_nth_1_1_lua_type_registration.html", null ],
      [ "LuaTypeTraits", "struct_nth_1_1_lua_type_traits.html", null ],
      [ "LuaTypeTraits< BehaviorEntity >", "struct_nth_1_1_lua_type_traits_3_01_behavior_entity_01_4.html", null ],
      [ "LuaTypeTraits< Clock >", "struct_nth_1_1_lua_type_traits_3_01_clock_01_4.html", null ],
      [ "LuaTypeTraits< SceneState >", "struct_nth_1_1_lua_type_traits_3_01_scene_state_01_4.html", null ],
      [ "LuaTypeTraits< Transform >", "struct_nth_1_1_lua_type_traits_3_01_transform_01_4.html", null ],
      [ "LuaTypeTraits< Vec2 >", "struct_nth_1_1_lua_type_traits_3_01_vec2_01_4.html", null ],
      [ "Math", "class_nth_1_1_math.html", "class_nth_1_1_math" ],
      [ "OpenGLException", "struct_nth_1_1_open_g_l_exception.html", "struct_nth_1_1_open_g_l_exception" ],
      [ "PhysicsDebugLayer", "class_nth_1_1_physics_debug_layer.html", "class_nth_1_1_physics_debug_layer" ],
      [ "PhysicsEngine", "class_nth_1_1_physics_engine.html", null ],
      [ "ProjectDescriptor", "struct_nth_1_1_project_descriptor.html", "struct_nth_1_1_project_descriptor" ],
      [ "ProjectRunner", "class_nth_1_1_project_runner.html", "class_nth_1_1_project_runner" ],
      [ "RenderContext", "class_nth_1_1_render_context.html", "class_nth_1_1_render_context" ],
      [ "Rigidbody2D", "struct_nth_1_1_rigidbody2_d.html", "struct_nth_1_1_rigidbody2_d" ],
      [ "Rigidbody2DDescriptor", "struct_nth_1_1_rigidbody2_d_descriptor.html", "struct_nth_1_1_rigidbody2_d_descriptor" ],
      [ "Scene", "class_nth_1_1_scene.html", "class_nth_1_1_scene" ],
      [ "SceneDescriptor", "struct_nth_1_1_scene_descriptor.html", "struct_nth_1_1_scene_descriptor" ],
      [ "SceneParser", "class_nth_1_1_scene_parser.html", null ],
      [ "SceneState", "class_nth_1_1_scene_state.html", "class_nth_1_1_scene_state" ],
      [ "ScriptEngine", "class_nth_1_1_script_engine.html", "class_nth_1_1_script_engine" ],
      [ "ScriptTypeRegistry", "class_nth_1_1_script_type_registry.html", null ],
      [ "SetUniformCommand", "struct_nth_1_1_set_uniform_command.html", "struct_nth_1_1_set_uniform_command" ],
      [ "SetViewportCommand", "struct_nth_1_1_set_viewport_command.html", "struct_nth_1_1_set_viewport_command" ],
      [ "Shader", "class_nth_1_1_shader.html", "class_nth_1_1_shader" ],
      [ "ShaderManager", "class_nth_1_1_shader_manager.html", null ],
      [ "SpriteRenderer", "struct_nth_1_1_sprite_renderer.html", "struct_nth_1_1_sprite_renderer" ],
      [ "SpriteRendererDescriptor", "struct_nth_1_1_sprite_renderer_descriptor.html", "struct_nth_1_1_sprite_renderer_descriptor" ],
      [ "SpriteVertex", "struct_nth_1_1_sprite_vertex.html", "struct_nth_1_1_sprite_vertex" ],
      [ "TextureManager", "class_nth_1_1_texture_manager.html", null ],
      [ "Transform", "struct_nth_1_1_transform.html", "struct_nth_1_1_transform" ],
      [ "TransformDescriptor", "struct_nth_1_1_transform_descriptor.html", "struct_nth_1_1_transform_descriptor" ],
      [ "VertexArray", "class_nth_1_1_vertex_array.html", "class_nth_1_1_vertex_array" ],
      [ "VertexAttribute", "struct_nth_1_1_vertex_attribute.html", "struct_nth_1_1_vertex_attribute" ],
      [ "VertexBuffer", "class_nth_1_1_vertex_buffer.html", "class_nth_1_1_vertex_buffer" ],
      [ "VertexLayout", "class_nth_1_1_vertex_layout.html", "class_nth_1_1_vertex_layout" ],
      [ "XmlMacroExpander", "class_nth_1_1_xml_macro_expander.html", "class_nth_1_1_xml_macro_expander" ]
    ] ],
    [ "std", null, [
      [ "hash< Nth::Color >", "structstd_1_1hash_3_01_nth_1_1_color_01_4.html", "structstd_1_1hash_3_01_nth_1_1_color_01_4" ]
    ] ]
];