var annotated_dup =
[
    [ "Astera", "namespace_astera.html", [
      [ "ArenaAllocator", "class_astera_1_1_arena_allocator.html", "class_astera_1_1_arena_allocator" ],
      [ "AssetManager", "class_astera_1_1_asset_manager.html", "class_astera_1_1_asset_manager" ],
      [ "AudioEngine", "class_astera_1_1_audio_engine.html", "class_astera_1_1_audio_engine" ],
      [ "Behavior", "struct_astera_1_1_behavior.html", "struct_astera_1_1_behavior" ],
      [ "BehaviorDescriptor", "struct_astera_1_1_behavior_descriptor.html", "struct_astera_1_1_behavior_descriptor" ],
      [ "BehaviorEntity", "struct_astera_1_1_behavior_entity.html", "struct_astera_1_1_behavior_entity" ],
      [ "BehaviorScriptContext", "struct_astera_1_1_behavior_script_context.html", "struct_astera_1_1_behavior_script_context" ],
      [ "BinaryWriter", "class_astera_1_1_binary_writer.html", "class_astera_1_1_binary_writer" ],
      [ "BindShaderCommand", "struct_astera_1_1_bind_shader_command.html", "struct_astera_1_1_bind_shader_command" ],
      [ "BindVertexArrayCommand", "struct_astera_1_1_bind_vertex_array_command.html", "struct_astera_1_1_bind_vertex_array_command" ],
      [ "Camera", "struct_astera_1_1_camera.html", null ],
      [ "ClearCommand", "struct_astera_1_1_clear_command.html", "struct_astera_1_1_clear_command" ],
      [ "Clock", "class_astera_1_1_clock.html", "class_astera_1_1_clock" ],
      [ "Collider2D", "struct_astera_1_1_collider2_d.html", null ],
      [ "CollisionDetection", "class_astera_1_1_collision_detection.html", null ],
      [ "Color", "class_astera_1_1_color.html", "class_astera_1_1_color" ],
      [ "CommandExecutor", "class_astera_1_1_command_executor.html", "class_astera_1_1_command_executor" ],
      [ "CommandQueue", "class_astera_1_1_command_queue.html", "class_astera_1_1_command_queue" ],
      [ "Content", "class_astera_1_1_content.html", null ],
      [ "DebugManager", "class_astera_1_1_debug_manager.html", "class_astera_1_1_debug_manager" ],
      [ "DrawArraysCommand", "struct_astera_1_1_draw_arrays_command.html", "struct_astera_1_1_draw_arrays_command" ],
      [ "DrawIndexedCommand", "struct_astera_1_1_draw_indexed_command.html", "struct_astera_1_1_draw_indexed_command" ],
      [ "DrawIndexedInstancedCommand", "struct_astera_1_1_draw_indexed_instanced_command.html", "struct_astera_1_1_draw_indexed_instanced_command" ],
      [ "DrawSpriteCommand", "struct_astera_1_1_draw_sprite_command.html", "struct_astera_1_1_draw_sprite_command" ],
      [ "EntityDescriptor", "struct_astera_1_1_entity_descriptor.html", "struct_astera_1_1_entity_descriptor" ],
      [ "FrameAllocator", "class_astera_1_1_frame_allocator.html", "class_astera_1_1_frame_allocator" ],
      [ "Game", "class_astera_1_1_game.html", "class_astera_1_1_game" ],
      [ "Geometry", "class_astera_1_1_geometry.html", "class_astera_1_1_geometry" ],
      [ "IBuffer", "class_astera_1_1_i_buffer.html", "class_astera_1_1_i_buffer" ],
      [ "IDebugOverlay", "class_astera_1_1_i_debug_overlay.html", "class_astera_1_1_i_debug_overlay" ],
      [ "ImGuiDebugLayer", "class_astera_1_1_im_gui_debug_layer.html", "class_astera_1_1_im_gui_debug_layer" ],
      [ "IndexBuffer", "class_astera_1_1_index_buffer.html", "class_astera_1_1_index_buffer" ],
      [ "InputManager", "class_astera_1_1_input_manager.html", "class_astera_1_1_input_manager" ],
      [ "IO", "class_astera_1_1_i_o.html", null ],
      [ "Log", "class_astera_1_1_log.html", "class_astera_1_1_log" ],
      [ "LuaRegisterable", "struct_astera_1_1_lua_registerable.html", "struct_astera_1_1_lua_registerable" ],
      [ "LuaRegistry", "struct_astera_1_1_lua_registry.html", "struct_astera_1_1_lua_registry" ],
      [ "LuaTypeRegistration", "struct_astera_1_1_lua_type_registration.html", null ],
      [ "LuaTypeTraits", "struct_astera_1_1_lua_type_traits.html", null ],
      [ "LuaTypeTraits< BehaviorEntity >", "struct_astera_1_1_lua_type_traits_3_01_behavior_entity_01_4.html", null ],
      [ "LuaTypeTraits< Clock >", "struct_astera_1_1_lua_type_traits_3_01_clock_01_4.html", null ],
      [ "LuaTypeTraits< SceneState >", "struct_astera_1_1_lua_type_traits_3_01_scene_state_01_4.html", null ],
      [ "LuaTypeTraits< Transform >", "struct_astera_1_1_lua_type_traits_3_01_transform_01_4.html", null ],
      [ "LuaTypeTraits< Vec2 >", "struct_astera_1_1_lua_type_traits_3_01_vec2_01_4.html", null ],
      [ "Math", "class_astera_1_1_math.html", "class_astera_1_1_math" ],
      [ "NotImplemented", "class_astera_1_1_not_implemented.html", "class_astera_1_1_not_implemented" ],
      [ "OpenGLException", "struct_astera_1_1_open_g_l_exception.html", "struct_astera_1_1_open_g_l_exception" ],
      [ "PhysicsDebugLayer", "class_astera_1_1_physics_debug_layer.html", "class_astera_1_1_physics_debug_layer" ],
      [ "PhysicsEngine", "class_astera_1_1_physics_engine.html", null ],
      [ "RenderContext", "class_astera_1_1_render_context.html", "class_astera_1_1_render_context" ],
      [ "Resource", "class_astera_1_1_resource.html", "class_astera_1_1_resource" ],
      [ "ResourceBase", "class_astera_1_1_resource_base.html", "class_astera_1_1_resource_base" ],
      [ "ResourceHandle", "class_astera_1_1_resource_handle.html", "class_astera_1_1_resource_handle" ],
      [ "ResourceLoader", "class_astera_1_1_resource_loader.html", "class_astera_1_1_resource_loader" ],
      [ "ResourceLoaderBase", "class_astera_1_1_resource_loader_base.html", "class_astera_1_1_resource_loader_base" ],
      [ "ResourceManager", "class_astera_1_1_resource_manager.html", "class_astera_1_1_resource_manager" ],
      [ "Rigidbody2D", "struct_astera_1_1_rigidbody2_d.html", "struct_astera_1_1_rigidbody2_d" ],
      [ "Rigidbody2DDescriptor", "struct_astera_1_1_rigidbody2_d_descriptor.html", "struct_astera_1_1_rigidbody2_d_descriptor" ],
      [ "Scene", "class_astera_1_1_scene.html", "class_astera_1_1_scene" ],
      [ "SceneDescriptor", "struct_astera_1_1_scene_descriptor.html", "struct_astera_1_1_scene_descriptor" ],
      [ "SceneParser", "class_astera_1_1_scene_parser.html", null ],
      [ "SceneState", "class_astera_1_1_scene_state.html", "class_astera_1_1_scene_state" ],
      [ "ScriptEngine", "class_astera_1_1_script_engine.html", "class_astera_1_1_script_engine" ],
      [ "ScriptTypeRegistry", "class_astera_1_1_script_type_registry.html", null ],
      [ "SetUniformCommand", "struct_astera_1_1_set_uniform_command.html", "struct_astera_1_1_set_uniform_command" ],
      [ "SetViewportCommand", "struct_astera_1_1_set_viewport_command.html", "struct_astera_1_1_set_viewport_command" ],
      [ "Shader", "class_astera_1_1_shader.html", "class_astera_1_1_shader" ],
      [ "ShaderManager", "class_astera_1_1_shader_manager.html", null ],
      [ "SpriteBatch", "struct_astera_1_1_sprite_batch.html", "struct_astera_1_1_sprite_batch" ],
      [ "SpriteInstanceData", "struct_astera_1_1_sprite_instance_data.html", "struct_astera_1_1_sprite_instance_data" ],
      [ "SpriteRenderer", "struct_astera_1_1_sprite_renderer.html", "struct_astera_1_1_sprite_renderer" ],
      [ "SpriteRendererDescriptor", "struct_astera_1_1_sprite_renderer_descriptor.html", "struct_astera_1_1_sprite_renderer_descriptor" ],
      [ "SpriteVertex", "struct_astera_1_1_sprite_vertex.html", "struct_astera_1_1_sprite_vertex" ],
      [ "TextureManager", "class_astera_1_1_texture_manager.html", null ],
      [ "Transform", "struct_astera_1_1_transform.html", "struct_astera_1_1_transform" ],
      [ "TransformDescriptor", "struct_astera_1_1_transform_descriptor.html", "struct_astera_1_1_transform_descriptor" ],
      [ "UnbindVertexArrayCommand", "struct_astera_1_1_unbind_vertex_array_command.html", null ],
      [ "UpdateIndexBufferCommand", "struct_astera_1_1_update_index_buffer_command.html", "struct_astera_1_1_update_index_buffer_command" ],
      [ "UpdateVertexBufferCommand", "struct_astera_1_1_update_vertex_buffer_command.html", "struct_astera_1_1_update_vertex_buffer_command" ],
      [ "VertexArray", "class_astera_1_1_vertex_array.html", "class_astera_1_1_vertex_array" ],
      [ "VertexAttribute", "struct_astera_1_1_vertex_attribute.html", "struct_astera_1_1_vertex_attribute" ],
      [ "VertexBuffer", "class_astera_1_1_vertex_buffer.html", "class_astera_1_1_vertex_buffer" ],
      [ "VertexLayout", "class_astera_1_1_vertex_layout.html", "class_astera_1_1_vertex_layout" ]
    ] ],
    [ "std", null, [
      [ "hash< Astera::Color >", "structstd_1_1hash_3_01_astera_1_1_color_01_4.html", "structstd_1_1hash_3_01_astera_1_1_color_01_4" ]
    ] ],
    [ "AssetSubcommand", "struct_asset_subcommand.html", null ],
    [ "ProjectSubcommand", "struct_project_subcommand.html", null ]
];