var hierarchy =
[
    [ "Astera::ArenaAllocator", "class_astera_1_1_arena_allocator.html", null ],
    [ "Astera::AssetManager", "class_astera_1_1_asset_manager.html", null ],
    [ "AssetSubcommand", "struct_asset_subcommand.html", null ],
    [ "Astera::AudioEngine", "class_astera_1_1_audio_engine.html", null ],
    [ "Astera::Behavior", "struct_astera_1_1_behavior.html", null ],
    [ "Astera::BehaviorDescriptor", "struct_astera_1_1_behavior_descriptor.html", null ],
    [ "Astera::BehaviorEntity", "struct_astera_1_1_behavior_entity.html", null ],
    [ "Astera::BehaviorScriptContext", "struct_astera_1_1_behavior_script_context.html", null ],
    [ "Astera::BinaryWriter", "class_astera_1_1_binary_writer.html", null ],
    [ "Astera::BindShaderCommand", "struct_astera_1_1_bind_shader_command.html", null ],
    [ "Astera::BindVertexArrayCommand", "struct_astera_1_1_bind_vertex_array_command.html", null ],
    [ "Astera::Camera", "struct_astera_1_1_camera.html", null ],
    [ "Astera::ClearCommand", "struct_astera_1_1_clear_command.html", null ],
    [ "Astera::Clock", "class_astera_1_1_clock.html", null ],
    [ "Astera::Collider2D", "struct_astera_1_1_collider2_d.html", null ],
    [ "Astera::CollisionDetection", "class_astera_1_1_collision_detection.html", null ],
    [ "Astera::Color", "class_astera_1_1_color.html", null ],
    [ "Astera::CommandExecutor", "class_astera_1_1_command_executor.html", null ],
    [ "Astera::CommandQueue", "class_astera_1_1_command_queue.html", null ],
    [ "Astera::Content", "class_astera_1_1_content.html", null ],
    [ "Astera::DebugManager", "class_astera_1_1_debug_manager.html", null ],
    [ "Astera::DrawArraysCommand", "struct_astera_1_1_draw_arrays_command.html", null ],
    [ "Astera::DrawIndexedCommand", "struct_astera_1_1_draw_indexed_command.html", null ],
    [ "Astera::DrawIndexedInstancedCommand", "struct_astera_1_1_draw_indexed_instanced_command.html", null ],
    [ "Astera::DrawSpriteCommand", "struct_astera_1_1_draw_sprite_command.html", null ],
    [ "Astera::EntityDescriptor", "struct_astera_1_1_entity_descriptor.html", null ],
    [ "std::exception", null, [
      [ "Astera::NotImplemented", "class_astera_1_1_not_implemented.html", null ]
    ] ],
    [ "Astera::FrameAllocator", "class_astera_1_1_frame_allocator.html", null ],
    [ "Astera::Geometry", "class_astera_1_1_geometry.html", null ],
    [ "std::hash< Astera::Color >", "structstd_1_1hash_3_01_astera_1_1_color_01_4.html", null ],
    [ "Astera::IBuffer", "class_astera_1_1_i_buffer.html", [
      [ "Astera::IndexBuffer", "class_astera_1_1_index_buffer.html", null ],
      [ "Astera::VertexBuffer", "class_astera_1_1_vertex_buffer.html", null ]
    ] ],
    [ "Astera::IDebugOverlay", "class_astera_1_1_i_debug_overlay.html", [
      [ "Astera::ImGuiDebugLayer", "class_astera_1_1_im_gui_debug_layer.html", null ],
      [ "Astera::PhysicsDebugLayer", "class_astera_1_1_physics_debug_layer.html", null ]
    ] ],
    [ "Astera::InputManager", "class_astera_1_1_input_manager.html", null ],
    [ "Astera::IO", "class_astera_1_1_i_o.html", null ],
    [ "Astera::JobSystem::JobCounter", "struct_astera_1_1_job_system_1_1_job_counter.html", null ],
    [ "Astera::JobSystem", "class_astera_1_1_job_system.html", null ],
    [ "Astera::Log", "class_astera_1_1_log.html", null ],
    [ "Astera::LuaRegisterable", "struct_astera_1_1_lua_registerable.html", [
      [ "Astera::LuaRegistry< T >", "struct_astera_1_1_lua_registry.html", null ]
    ] ],
    [ "Astera::LuaTypeRegistration< T >", "struct_astera_1_1_lua_type_registration.html", null ],
    [ "Astera::LuaTypeTraits< T, typename >", "struct_astera_1_1_lua_type_traits.html", null ],
    [ "Astera::LuaTypeTraits< BehaviorEntity >", "struct_astera_1_1_lua_type_traits_3_01_behavior_entity_01_4.html", null ],
    [ "Astera::LuaTypeTraits< Clock >", "struct_astera_1_1_lua_type_traits_3_01_clock_01_4.html", null ],
    [ "Astera::LuaTypeTraits< SceneState >", "struct_astera_1_1_lua_type_traits_3_01_scene_state_01_4.html", null ],
    [ "Astera::LuaTypeTraits< Transform >", "struct_astera_1_1_lua_type_traits_3_01_transform_01_4.html", null ],
    [ "Astera::LuaTypeTraits< Vec2 >", "struct_astera_1_1_lua_type_traits_3_01_vec2_01_4.html", null ],
    [ "Astera::Math", "class_astera_1_1_math.html", null ],
    [ "Astera::PhysicsEngine", "class_astera_1_1_physics_engine.html", null ],
    [ "ProjectSubcommand", "struct_project_subcommand.html", null ],
    [ "Astera::RenderContext", "class_astera_1_1_render_context.html", null ],
    [ "Astera::RenderTarget", "class_astera_1_1_render_target.html", null ],
    [ "Astera::RenderTargetConfig", "struct_astera_1_1_render_target_config.html", null ],
    [ "Astera::ResourceBase", "class_astera_1_1_resource_base.html", [
      [ "Astera::Resource< T >", "class_astera_1_1_resource.html", null ]
    ] ],
    [ "Astera::ResourceHandle< T >", "class_astera_1_1_resource_handle.html", null ],
    [ "Astera::ResourceLoaderBase", "class_astera_1_1_resource_loader_base.html", [
      [ "Astera::ResourceLoader< T >", "class_astera_1_1_resource_loader.html", null ]
    ] ],
    [ "Astera::ResourceManager", "class_astera_1_1_resource_manager.html", null ],
    [ "Astera::Rigidbody2D", "struct_astera_1_1_rigidbody2_d.html", null ],
    [ "Astera::Rigidbody2DDescriptor", "struct_astera_1_1_rigidbody2_d_descriptor.html", null ],
    [ "std::runtime_error", null, [
      [ "Astera::OpenGLException", "struct_astera_1_1_open_g_l_exception.html", null ]
    ] ],
    [ "Astera::Scene", "class_astera_1_1_scene.html", null ],
    [ "Astera::SceneDescriptor", "struct_astera_1_1_scene_descriptor.html", null ],
    [ "Astera::SceneParser", "class_astera_1_1_scene_parser.html", null ],
    [ "Astera::SceneState", "class_astera_1_1_scene_state.html", null ],
    [ "Astera::ScriptEngine", "class_astera_1_1_script_engine.html", null ],
    [ "Astera::ScriptTypeRegistry", "class_astera_1_1_script_type_registry.html", null ],
    [ "Astera::SetUniformCommand", "struct_astera_1_1_set_uniform_command.html", null ],
    [ "Astera::SetViewportCommand", "struct_astera_1_1_set_viewport_command.html", null ],
    [ "Astera::Shader", "class_astera_1_1_shader.html", null ],
    [ "Astera::ShaderManager", "class_astera_1_1_shader_manager.html", null ],
    [ "Astera::SpriteBatch", "struct_astera_1_1_sprite_batch.html", null ],
    [ "Astera::SpriteInstanceData", "struct_astera_1_1_sprite_instance_data.html", null ],
    [ "Astera::SpriteRenderer", "struct_astera_1_1_sprite_renderer.html", null ],
    [ "Astera::SpriteRendererDescriptor", "struct_astera_1_1_sprite_renderer_descriptor.html", null ],
    [ "Astera::SpriteVertex", "struct_astera_1_1_sprite_vertex.html", null ],
    [ "Astera::JobSystem::Statistics", "struct_astera_1_1_job_system_1_1_statistics.html", null ],
    [ "Astera::TextureManager", "class_astera_1_1_texture_manager.html", null ],
    [ "Astera::Transform", "struct_astera_1_1_transform.html", null ],
    [ "Astera::TransformDescriptor", "struct_astera_1_1_transform_descriptor.html", null ],
    [ "Astera::UnbindVertexArrayCommand", "struct_astera_1_1_unbind_vertex_array_command.html", null ],
    [ "Astera::UpdateIndexBufferCommand", "struct_astera_1_1_update_index_buffer_command.html", null ],
    [ "Astera::UpdateVertexBufferCommand", "struct_astera_1_1_update_vertex_buffer_command.html", null ],
    [ "Astera::VertexArray", "class_astera_1_1_vertex_array.html", null ],
    [ "Astera::VertexAttribute", "struct_astera_1_1_vertex_attribute.html", null ],
    [ "Astera::VertexLayout", "class_astera_1_1_vertex_layout.html", null ],
    [ "Astera::Window", "class_astera_1_1_window.html", [
      [ "Astera::Game", "class_astera_1_1_game.html", null ]
    ] ],
    [ "Astera::WindowConfig", "struct_astera_1_1_window_config.html", null ]
];