---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by conta.
--- DateTime: 12/3/2025 4:47 AM
---

---@class Clock High-precision timing and frame rate tracking
local Clock = {}

---Get delta time with double precision
---@return number Delta time in seconds (double precision)
function Clock:GetDeltaTimePrecise()
end

---Get delta time with single precision
---@return number Delta time in seconds (float precision)
function Clock:GetDeltaTime()
end

---Get total elapsed time since clock started
---@return number Total time in seconds
function Clock:GetTotalTime()
end

---Get current frames per second
---@return number Current FPS
function Clock:GetFramesPerSecond()
end

---Get raw performance counter value
---@return number Raw counter value
function Clock:GetRawCounter()
end

---Get performance counter frequency
---@return number Counter frequency
function Clock:GetCounterFrequency()
end

return Clock