---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by conta.
--- DateTime: 12/3/2025 4:47 AM
---

---@class Coordinates Coordinate system conversion utilities
Coordinates = {}

---Convert screen pixel coordinates to NDC (Normalized Device Coordinates)
---@param screenPos Vec2 Position in screen space (pixels)
---@param screenWidth number Width of the screen in pixels
---@param screenHeight number Height of the screen in pixels
---@return Vec2 Position in NDC space [-1, 1]
function Coordinates:ScreenToNDC(screenPos, screenWidth, screenHeight)
end

---Convert NDC coordinates to screen pixel coordinates
---@param ndcPos Vec2 Position in NDC space [-1, 1]
---@param screenWidth number Width of the screen in pixels
---@param screenHeight number Height of the screen in pixels
---@return Vec2 Position in screen space (pixels)
function Coordinates:NDCToScreen(ndcPos, screenWidth, screenHeight)
end

---Convert screen pixel coordinates to world space (using orthographic projection)
---@param screenPos Vec2 Position in screen space (pixels)
---@param screenWidth number Width of the screen in pixels
---@param screenHeight number Height of the screen in pixels
---@param worldLeft? number Left bound of world space (default 0)
---@param worldRight? number Right bound of world space (default screenWidth)
---@param worldBottom? number Bottom bound of world space (default 0)
---@param worldTop? number Top bound of world space (default screenHeight)
---@return Vec2 Position in world space
function Coordinates:ScreenToWorld(screenPos, screenWidth, screenHeight, worldLeft, worldRight, worldBottom, worldTop)
end

---Convert world space coordinates to screen pixels
---@param worldPos Vec2 Position in world space
---@param screenWidth number Width of the screen in pixels
---@param screenHeight number Height of the screen in pixels
---@param worldLeft? number Left bound of world space (default 0)
---@param worldRight? number Right bound of world space (default screenWidth)
---@param worldBottom? number Bottom bound of world space (default 0)
---@param worldTop? number Top bound of world space (default screenHeight)
---@return Vec2 Position in screen space (pixels)
function Coordinates:WorldToScreen(worldPos, screenWidth, screenHeight, worldLeft, worldRight, worldBottom, worldTop)
end

---Convert normalized coordinates [0, 1] to screen pixels
---@param normalizedPos Vec2 Position in normalized space [0, 1]
---@param screenWidth number Width of the screen in pixels
---@param screenHeight number Height of the screen in pixels
---@return Vec2 Position in screen space (pixels)
function Coordinates:NormalizedToScreen(normalizedPos, screenWidth, screenHeight)
end

---Convert screen pixels to normalized coordinates [0, 1]
---@param screenPos Vec2 Position in screen space (pixels)
---@param screenWidth number Width of the screen in pixels
---@param screenHeight number Height of the screen in pixels
---@return Vec2 Position in normalized space [0, 1]
function Coordinates:ScreenToNormalized(screenPos, screenWidth, screenHeight)
end

---Create an orthographic projection matrix for 2D rendering
---@param left number Left bound
---@param right number Right bound
---@param bottom number Bottom bound
---@param top number Top bound
---@param near? number Near clipping plane (default -1)
---@param far? number Far clipping plane (default 1)
---@return any Orthographic projection matrix (Mat4)
function Coordinates:CreateOrthoProjection(left, right, bottom, top, near, far)
end

---Create an orthographic projection matrix that matches screen dimensions
---@param screenWidth number Width of the screen in pixels
---@param screenHeight number Height of the screen in pixels
---@param originTopLeft? boolean If true, origin is at top-left; if false, origin is at bottom-left (default false)
---@return any Orthographic projection matrix (Mat4)
function Coordinates:CreateScreenProjection(screenWidth, screenHeight, originTopLeft)
end

---Get the aspect ratio of the screen
---@param screenWidth number Width of the screen in pixels
---@param screenHeight number Height of the screen in pixels
---@return number Aspect ratio (width / height)
function Coordinates:GetAspectRatio(screenWidth, screenHeight)
end

---Clamp a position to screen bounds
---@param pos Vec2 Position to clamp
---@param screenWidth number Width of the screen in pixels
---@param screenHeight number Height of the screen in pixels
---@return Vec2 Clamped position
function Coordinates:ClampToScreen(pos, screenWidth, screenHeight)
end

---Check if a position is within screen bounds
---@param pos Vec2 Position to check
---@param screenWidth number Width of the screen in pixels
---@param screenHeight number Height of the screen in pixels
---@return boolean True if position is within bounds
function Coordinates:IsOnScreen(pos, screenWidth, screenHeight)
end

---Convert mouse coordinates (usually top-left origin) to world space
---@param mousePos Vec2 Mouse position from input system
---@param screenWidth number Width of the screen in pixels
---@param screenHeight number Height of the screen in pixels
---@param originTopLeft? boolean Whether your world space has origin at top-left (default false)
---@return Vec2 Position in world space
function Coordinates:MouseToWorld(mousePos, screenWidth, screenHeight, originTopLeft)
end

return Coordinates