---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by conta.
--- DateTime: 12/3/2025 4:47 AM
---

---@class Entity Behavior entity with transform component
---@field name string The name of the entity
---@field transform Transform Reference to the entity's transform component
local Entity = {}

return Entity