---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by conta.
--- DateTime: 12/3/2025 4:47 AM
---

---@class Game Current running game instance
local Game = {}

---Quit the game
function Game:Quit()
end

---Return the screen size
---@return Vec2
function Game:GetScreenSize()
end

--- Loads a scene and returns true if succeeds
---@param name string
---@return boolean
function Game:LoadScene(name)
end

return Game