---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jr.
--- DateTime: 12/3/25 5:34 AM
---

---@class KeyCode Keyboard key codes
KeyCode = {
    A = 65,
    B = 66,
    C = 67,
    D = 68,
    E = 69,
    F = 70,
    G = 71,
    H = 72,
    I = 73,
    J = 74,
    K = 75,
    L = 76,
    M = 77,
    N = 78,
    O = 79,
    P = 80,
    Q = 81,
    R = 82,
    S = 83,
    T = 84,
    U = 85,
    V = 86,
    W = 87,
    X = 88,
    Y = 89,
    Z = 90,
    ["1"] = 49,
    ["2"] = 50,
    ["3"] = 51,
    ["4"] = 52,
    ["5"] = 53,
    ["6"] = 54,
    ["7"] = 55,
    ["8"] = 56,
    ["9"] = 57,
    ["0"] = 48,
    Minus = 0,
    Equal = 0,
    Backspace = 0,
    Tab = 0,
    Home = 0,
    Left = 0,
    Up = 0,
    Right = 0,
    Down = 0,
    Escape = 0,
    Enter = 0,
    Space = 32,
    LeftCtrl = 0,
    RightCtrl = 0,
    F1 = 0,
    F2 = 0,
    F3 = 0,
    F4 = 0,
    F5 = 0,
    F6 = 0,
    F7 = 0,
    F8 = 0,
    F9 = 0,
    F10 = 0,
    F11 = 0,
    F12 = 0,
}

---@class MouseButton Mouse button codes
MouseButton = {
    Left = 0,
    Right = 1,
    Middle = 2,
}

---@class InputManager Input management system
local InputManager = {}

---Check if a key is currently pressed
---@param key number Key code from KeyCode table
---@return boolean True if key is pressed
function InputManager:GetKeyDown(key)
end

---Check if a key was just released
---@param key number Key code from KeyCode table
---@return boolean True if key was released
function InputManager:GetKeyUp(key)
end

---Check if a mouse button is currently pressed
---@param button number Button code from MouseButton table
---@return boolean True if button is pressed
function InputManager:GetMouseButtonDown(button)
end

---Check if a mouse button was just released
---@param button number Button code from MouseButton table
---@return boolean True if button was released
function InputManager:GetMouseButtonUp(button)
end

---Get current mouse X position
---@return number Mouse X coordinate
function InputManager:GetMouseX()
end

---Get current mouse Y position
---@return number Mouse Y coordinate
function InputManager:GetMouseY()
end

---Get mouse X movement delta
---@return number Mouse X delta
function InputManager:GetMouseDeltaX()
end

---Get mouse Y movement delta
---@return number Mouse Y delta
function InputManager:GetMouseDeltaY()
end

---@type InputManager Global input manager instance
Input = {}

return InputManager