---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jr.
--- DateTime: 12/3/25 5:34 AM
---

---@class Log Engine logging class
local Log = {}

---Log with Debug severity
---@param msg string
function Log:Debug(msg)
end

---Log with Info severity
---@param msg string
function Log:Info(msg)
end

---Log with Warn severity
---@param msg string
function Log:Warn(msg)
end

---Log with Error severity
---@param msg string
function Log:Error(msg)
end

---Log with Critical severity
---@param msg string
function Log:Critical(msg)
end

return Log