---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by conta.
--- DateTime: 12/3/2025 4:47 AM
---

---@class Transform Spatial transformation component
---@field position Vec2 World position
---@field rotation number Rotation in radians
---@field scale Vec2 Scale factor
local Transform = {}

---Translate the transform by a delta
---@param delta Vec2 Translation offset
function Transform:Translate(delta)
end

---Rotate the transform by an angle
---@param angle number Rotation angle in radians
function Transform:Rotate(angle)
end

---Scale the transform by a factor
---@param factor Vec2 Scale multiplier
function Transform:Scale(factor)
end

return Transform