---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jr.
--- DateTime: 12/2/25 4:43 AM
---

ballSpeed = 500

---@param this Entity
function onAwake(this)
    Log:Debug(string.format("onAwake() called for entity: %s", this.name))
end

---@param transform Transform
---@param dT number
function handleMovement(transform, dT)
    local newPosition = Vec2(0, 0)

    -- Check is one of our movement keys is pressed
    if Input:GetKeyDown(KeyCode.W) then
        -- Apply a new value to the correct axis scaled by delta time
        newPosition.y = (ballSpeed * dT)
    end
    if Input:GetKeyDown(KeyCode.S) then
        newPosition.y = -(ballSpeed * dT)
    end
    if Input:GetKeyDown(KeyCode.A) then
        newPosition.x = -(ballSpeed * dT)
    end
    if Input:GetKeyDown(KeyCode.D) then
        newPosition.x = (ballSpeed * dT)
    end

    -- Translate our entity by the corresponding new amount
    transform:Translate(newPosition)
end

---@param this Entity
---@param clock Clock
function onUpdate(this, clock)
    handleMovement(this.transform, clock:GetDeltaTime())
end

---@param this Entity
function onDestroyed(this)
    Log:Debug(string.format("onDestroyed() called for entity: %s", this.name))
end
