---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jr.
--- DateTime: 12/2/25 4:43 AM
---

ballSpeed = 500

function onAwake(this)
    Log:Debug(string.format("onAwake() called for entity: %s", this.name))

    local screenSize = Game:GetScreenSize()
    local screenPos = Vec2(320, 180)
    local toNDC = Coordinates:ScreenToNDC(screenPos, screenSize.x, screenSize.y)
    Log:Debug(string.format("NDC Pos: {x: %f, y: %f}", toNDC.x, toNDC.y))
end

function handleMovement(transform, dT)
    local newPosition = Vec2(0, 0)

    -- Check is one of our movement keys is pressed
    if Input:GetKeyDown(KEY_W) then
        -- Apply a new value to the correct axis scaled by delta time
        newPosition.y = (ballSpeed * dT)
    end
    if Input:GetKeyDown(KEY_S) then
        newPosition.y = -(ballSpeed * dT)
    end
    if Input:GetKeyDown(KEY_A) then
        newPosition.x = -(ballSpeed * dT)
    end
    if Input:GetKeyDown(KEY_D) then
        newPosition.x = (ballSpeed * dT)
    end

    -- Translate our entity by the corresponding new amount
    transform:Translate(newPosition)
end

function onUpdate(this, clock)
    handleMovement(this.transform, clock:GetDeltaTime())
end

function onDestroyed(this)
    Log:Debug(string.format("onDestroyed() called for entity: %s", this.name))
end
