---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jr.
--- DateTime: 12/2/25 4:43 AM
---

function OnAwake(entity)

end

function OnUpdate(entity, clock)

end

function OnDestroyed(entity)

end