---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jr.
--- DateTime: 12/2/25 4:43 AM
---

function onAwake(entity)
    print("LuaInterpreter: onAwake() was called")
end

function onUpdate(entity, clock)
    transform = entity.transform
    print(string.format("LuaInterpreter: Position: x: %.1f, y: %.1f", transform.Position.x, transform.Position.y))
end

function onDestroyed(entity)
    print("LuaInterpreter: onDestroyed() was called")
end