---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jr.
--- DateTime: 12/2/25 4:43 AM
---

function onAwake(entity)
    print("LuaInterpreter: onAwake() was called")
end

function onUpdate(entity, clock)
    local transform = entity.transform
    local deltaX = Vec2(0.1, 0.0)
    transform:Translate(deltaX)
end

function onDestroyed(entity)
    print("LuaInterpreter: onDestroyed() was called")
end